#!/usr/bin/env python3
"""
Script para verificar y poblar la tabla de centros en Supabase.
Este script:
1. Verifica la estructura de la tabla center
2. Crea/agrega centros por cliente según las especificaciones
3. Muestra la estructura actual
"""
import os
import sys
from datetime import datetime

# Add current directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Importar desde main.py
from main import app
from models.models import db, Client
from sqlalchemy import text, inspect

def check_center_table_structure():
    """Verifica si la tabla center existe y muestra su estructura"""
    with app.app_context():
        print("=" * 60)
        print("VERIFICANDO ESTRUCTURA DE TABLA 'center'")
        print("=" * 60)

        try:
            # Verificar si la tabla existe
            inspector = inspect(db.engine)
            if 'center' not in inspector.get_table_names():
                print("\n❌ La tabla 'center' NO existe en Supabase")
                print("\nPor favor, crea la tabla manualmente con:")
                print("""
CREATE TABLE public.center (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(client_id, name)
);

CREATE INDEX idx_center_client_id ON center(client_id);
                """)
                return False

            # Obtener columnas
            columns = inspector.get_columns('center')
            print("\n✅ Tabla 'center' EXISTE")
            print("\nEstructura de columnas:")
            for col in columns:
                print(f"  • {col['name']}: {col['type']}")

            return True

        except Exception as e:
            print(f"\n❌ Error verificando tabla: {e}")
            return False


def check_center_data():
    """Verifica los datos actuales en la tabla center"""
    with app.app_context():
        print("\n" + "=" * 60)
        print("DATOS ACTUALES EN TABLA 'center'")
        print("=" * 60)

        try:
            result = db.session.execute(text("""
                SELECT id, client_id, name
                FROM center
                ORDER BY client_id, name
            """))
            rows = result.fetchall()

            if not rows:
                print("\n⚠️  No hay datos en la tabla center")
                return []

            print(f"\nTotal de centros: {len(rows)}\n")
            for row_id, client_id, name in rows:
                print(f"  ID: {row_id} | Client: {client_id} | Nombre: {name}")

            return rows

        except Exception as e:
            print(f"\n❌ Error consultando datos: {e}")
            return []


def add_missing_centers():
    """Agrega los centros faltantes según las especificaciones"""
    with app.app_context():
        print("\n" + "=" * 60)
        print("AGREGANDO CENTROS FALTANTES")
        print("=" * 60)

        # Definir centros por cliente
        centers_spec = {
            1: ["Centro 1", "Centro 2", "Centro 3"],
            2: ["La esquina del paisa"],
            4: ["Cliente de ejemplo 4"]
        }

        # Obtener centros existentes
        existing = {}
        result = db.session.execute(text("""
            SELECT client_id, name FROM center
        """))
        for client_id, name in result.fetchall():
            if client_id not in existing:
                existing[client_id] = set()
            existing[client_id].add(name)

        print(f"\nCentros existentes por cliente:")
        for cid in sorted(existing.keys()):
            print(f"  client_id={cid}: {existing[cid]}")

        # Agregar centros faltantes
        added_count = 0
        for client_id, centers in centers_spec.items():
            if client_id not in existing:
                existing[client_id] = set()

            print(f"\n📊 Client ID: {client_id}")
            for center_name in centers:
                if center_name not in existing[client_id]:
                    try:
                        db.session.execute(text("""
                            INSERT INTO center (client_id, name, is_active)
                            VALUES (:client_id, :name, :is_active)
                        """), {
                            "client_id": client_id,
                            "name": center_name,
                            "is_active": True
                        })
                        print(f"  ✅ Agregado: {center_name}")
                        added_count += 1
                    except Exception as e:
                        print(f"  ❌ Error agregando {center_name}: {e}")
                        db.session.rollback()
                else:
                    print(f"  ✓ Existente: {center_name}")

        if added_count > 0:
            db.session.commit()
            print(f"\n✅ {added_count} centros agregados exitosamente")
        else:
            print("\n✓ Todos los centros ya existen")


def show_centers_by_client():
    """Muestra los centros agrupados por cliente"""
    with app.app_context():
        print("\n" + "=" * 60)
        print("CENTROS AGRUPADOS POR CLIENTE")
        print("=" * 60)

        clients = Client.query.all()

        for client in clients:
            result = db.session.execute(text("""
                SELECT id, name FROM center
                WHERE client_id = :client_id
                ORDER BY name
            """), {"client_id": client.id})
            centers = result.fetchall()

            print(f"\n📊 {client.name} (client_id={client.id})")
            if centers:
                for center_id, center_name in centers:
                    print(f"   • ID: {center_id} | {center_name}")
            else:
                print("   ⚠️  Sin centros configurados")


if __name__ == '__main__':
    print("\n🚀 Starting Center Verification and Setup Script...\n")

    # Step 1: Check table structure
    if not check_center_table_structure():
        print("\n❌ Por favor, crea la tabla 'center' en Supabase primero")
        sys.exit(1)

    # Step 2: Check current data
    check_center_data()

    # Step 3: Add missing centers
    add_missing_centers()

    # Step 4: Show final result
    show_centers_by_client()

    print("\n" + "=" * 60)
    print("✅ VERIFICACIÓN Y SETUP COMPLETADO")
    print("=" * 60)
    print("\nPróximos pasos:")
    print("1. Actualizar modelo User para agregar center_id FK")
    print("2. Crear migraciones Alembic")
    print("3. Migrar datos de User.centro → User.center_id")
    print("4. Actualizar templates para selectores dinámicos")
    print()
