"""Remove theme_preference column from User model

Revision ID: 73245cfbcc7e
Revises: a42308d64561
Create Date: 2025-12-05 19:24:10.456649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73245cfbcc7e'
down_revision = 'a42308d64561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.VARCHAR(length=50), server_default=sa.text("'dark-turquoise'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
