"""Remove: Eliminar columna theme_preference no utilizada

Revision ID: a42308d64561
Revises: fix_audit_system_001
Create Date: 2025-12-05 18:50:52.775448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a42308d64561'
down_revision = 'fix_audit_system_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_record_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_log_changed_at'))
        batch_op.drop_index(batch_op.f('idx_audit_log_operation'))
        batch_op.drop_index(batch_op.f('idx_audit_log_time_record'))

    op.drop_table('time_record_audit_log')
    with op.batch_alter_table('inspector_access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_inspector_log_accessed'))
        batch_op.drop_index(batch_op.f('idx_inspector_log_action'))
        batch_op.drop_index(batch_op.f('idx_inspector_log_client'))
        batch_op.drop_index(batch_op.f('idx_inspector_log_token'))

    op.drop_table('inspector_access_log')
    with op.batch_alter_table('inspector_access_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_inspector_token_active'))
        batch_op.drop_index(batch_op.f('idx_inspector_token_client'))
        batch_op.drop_index(batch_op.f('idx_inspector_token_token'))

    op.drop_table('inspector_access_token')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('category_client_id_name_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_category_client_id'))
        batch_op.create_unique_constraint('uix_client_category_name', ['client_id', 'name'])

    with op.batch_alter_table('center', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_client_center_name', ['client_id', 'name'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('brand_name')

    with op.batch_alter_table('email_notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_email_log_sent_at'))
        batch_op.drop_index(batch_op.f('idx_email_log_type_date'))
        batch_op.drop_index(batch_op.f('idx_email_log_user_id'))

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.alter_column('request_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Vacaciones', 'Baja médica', 'Ausencia justificada', 'Ausencia injustificada', 'Permiso especial', name='leave_type_enum'),
               existing_nullable=False,
               postgresql_using='request_type::leave_type_enum')
        batch_op.alter_column('attachment_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL del archivo adjunto en Supabase Storage',
               existing_nullable=True)
        batch_op.alter_column('attachment_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nombre original del archivo',
               existing_nullable=True)
        batch_op.alter_column('attachment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo MIME del archivo (application/pdf, image/jpeg, etc.)',
               existing_nullable=True)
        batch_op.alter_column('attachment_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tamaño del archivo en bytes',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_leave_request_attachment'), postgresql_where='(attachment_url IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_leave_request_created_at'))
        batch_op.drop_index(batch_op.f('idx_leave_request_dates'))
        batch_op.drop_index(batch_op.f('idx_leave_request_status'))
        batch_op.drop_index(batch_op.f('idx_leave_request_user_id'))

    with op.batch_alter_table('overtime_entry', schema=None) as batch_op:
        batch_op.alter_column('decided_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('overtime_entry_decided_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['decided_by'], ['id'])

    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_time_record_client_date'))
        batch_op.drop_index(batch_op.f('idx_time_record_is_active'))
        batch_op.drop_index(batch_op.f('idx_time_record_user_date'))
        batch_op.drop_constraint(batch_op.f('time_record_replaced_by_id_fkey'), type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('correction_reason')
        batch_op.drop_column('replaced_by_id')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('time_record_signature', schema=None) as batch_op:
        batch_op.alter_column('timestamp_utc',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp preciso UTC del servidor en el momento exacto del fichaje',
               existing_nullable=False)
        batch_op.alter_column('terminal_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identificador del terminal origen (ej: web_192.168.1.1, mobile_app)',
               existing_nullable=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               comment=None,
               existing_comment='Hash SHA-256 del contenido en formato hexadecimal (64 caracteres)',
               existing_nullable=False)
        batch_op.alter_column('signature',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               comment=None,
               existing_comment='Firma HMAC-SHA256 del hash en formato hexadecimal (64 caracteres)',
               existing_nullable=False)
        batch_op.alter_column('key_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Versión de la clave HMAC usada, permite rotación de claves',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('idx_time_record_signature_action'))
        batch_op.drop_index(batch_op.f('idx_time_record_signature_client_id'))
        batch_op.drop_index(batch_op.f('idx_time_record_signature_client_timestamp'))
        batch_op.drop_index(batch_op.f('idx_time_record_signature_time_record_id'))
        batch_op.drop_index(batch_op.f('idx_time_record_signature_timestamp'))
        batch_op.drop_table_comment(
        existing_comment='Sellos de tiempo con firma digital para fichajes. Cumple Ley de Fichajes.'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_center_id'))

    with op.batch_alter_table('work_pause', schema=None) as batch_op:
        batch_op.alter_column('pause_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Descanso', 'Hora del almuerzo', 'Asuntos médicos', 'Desplazamientos', 'Otros', name='pause_type_enum'),
               existing_nullable=False,
               postgresql_using='pause_type::pause_type_enum')
        batch_op.alter_column('attachment_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL del archivo adjunto en Supabase Storage',
               existing_nullable=True)
        batch_op.alter_column('attachment_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nombre original del archivo',
               existing_nullable=True)
        batch_op.alter_column('attachment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo MIME del archivo (application/pdf, image/jpeg, etc.)',
               existing_nullable=True)
        batch_op.alter_column('attachment_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tamaño del archivo en bytes',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_work_pause_attachment'), postgresql_where='(attachment_url IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_work_pause_date'))
        batch_op.drop_index(batch_op.f('idx_work_pause_pause_end'))
        batch_op.drop_index(batch_op.f('idx_work_pause_time_record_id'))
        batch_op.drop_index(batch_op.f('idx_work_pause_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_pause', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_work_pause_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_work_pause_time_record_id'), ['time_record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_work_pause_pause_end'), ['pause_end'], unique=False)
        batch_op.create_index(batch_op.f('idx_work_pause_date'), ['pause_start'], unique=False)
        batch_op.create_index(batch_op.f('idx_work_pause_attachment'), ['attachment_url'], unique=False, postgresql_where='(attachment_url IS NOT NULL)')
        batch_op.alter_column('attachment_size',
               existing_type=sa.INTEGER(),
               comment='Tamaño del archivo en bytes',
               existing_nullable=True)
        batch_op.alter_column('attachment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo MIME del archivo (application/pdf, image/jpeg, etc.)',
               existing_nullable=True)
        batch_op.alter_column('attachment_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Nombre original del archivo',
               existing_nullable=True)
        batch_op.alter_column('attachment_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL del archivo adjunto en Supabase Storage',
               existing_nullable=True)
        batch_op.alter_column('pause_type',
               existing_type=sa.Enum('Descanso', 'Hora del almuerzo', 'Asuntos médicos', 'Desplazamientos', 'Otros', name='pause_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='pause_type::text')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_center_id'), ['center_id'], unique=False)

    with op.batch_alter_table('time_record_signature', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Sellos de tiempo con firma digital para fichajes. Cumple Ley de Fichajes.',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_time_record_signature_timestamp'), [sa.literal_column('timestamp_utc DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_signature_time_record_id'), ['time_record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_signature_client_timestamp'), ['client_id', sa.literal_column('timestamp_utc DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_signature_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_signature_action'), ['action'], unique=False)
        batch_op.alter_column('key_version',
               existing_type=sa.INTEGER(),
               comment='Versión de la clave HMAC usada, permite rotación de claves',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('signature',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               comment='Firma HMAC-SHA256 del hash en formato hexadecimal (64 caracteres)',
               existing_nullable=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               comment='Hash SHA-256 del contenido en formato hexadecimal (64 caracteres)',
               existing_nullable=False)
        batch_op.alter_column('terminal_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Identificador del terminal origen (ej: web_192.168.1.1, mobile_app)',
               existing_nullable=False)
        batch_op.alter_column('timestamp_utc',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp preciso UTC del servidor en el momento exacto del fichaje',
               existing_nullable=False)

    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('replaced_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correction_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('time_record_replaced_by_id_fkey'), 'time_record', ['replaced_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_time_record_user_date'), ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_time_record_client_date'), ['client_id', 'date'], unique=False)

    with op.batch_alter_table('overtime_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('overtime_entry_decided_by_fkey'), 'user', ['decided_by'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('decided_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_leave_request_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_leave_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_leave_request_dates'), ['start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_leave_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_leave_request_attachment'), ['attachment_url'], unique=False, postgresql_where='(attachment_url IS NOT NULL)')
        batch_op.alter_column('attachment_size',
               existing_type=sa.INTEGER(),
               comment='Tamaño del archivo en bytes',
               existing_nullable=True)
        batch_op.alter_column('attachment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo MIME del archivo (application/pdf, image/jpeg, etc.)',
               existing_nullable=True)
        batch_op.alter_column('attachment_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Nombre original del archivo',
               existing_nullable=True)
        batch_op.alter_column('attachment_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL del archivo adjunto en Supabase Storage',
               existing_nullable=True)
        batch_op.alter_column('request_type',
               existing_type=sa.Enum('Vacaciones', 'Baja médica', 'Ausencia justificada', 'Ausencia injustificada', 'Permiso especial', name='leave_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='request_type::text')

    with op.batch_alter_table('email_notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_email_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_email_log_type_date'), ['notification_type', 'sent_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_email_log_sent_at'), ['sent_at'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('center', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_client_center_name', type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uix_client_category_name', type_='unique')
        batch_op.create_index(batch_op.f('idx_category_client_id'), ['client_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('category_client_id_name_key'), ['client_id', 'name'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    op.create_table('inspector_access_token',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('inspector_access_token_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Token UUID único para autenticación de inspectores'),
    sa.Column('valid_from', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('allowed_date_from', sa.DATE(), autoincrement=False, nullable=True, comment='Fecha mínima que el inspector puede consultar (ámbito de datos)'),
    sa.Column('allowed_date_to', sa.DATE(), autoincrement=False, nullable=True, comment='Fecha máxima que el inspector puede consultar (ámbito de datos)'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='inspector_access_token_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='inspector_access_token_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='inspector_access_token_pkey'),
    sa.UniqueConstraint('token', name='inspector_access_token_token_key'),
    comment='Tokens de acceso temporal para Inspección de Trabajo. Cumplimiento ley 2026.',
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('inspector_access_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inspector_token_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_inspector_token_client'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inspector_token_active'), ['is_active', 'valid_until'], unique=False)

    op.create_table('inspector_access_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filters_used', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Filtros JSON utilizados en la consulta (fechas, usuarios, etc.)'),
    sa.Column('records_accessed', sa.INTEGER(), autoincrement=False, nullable=True, comment='Número total de registros consultados o descargados'),
    sa.Column('accessed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('inspector_access_log_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['inspector_access_token.id'], name=op.f('inspector_access_log_token_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inspector_access_log_pkey')),
    comment='Registro completo de todos los accesos de inspectores. Auditoría de consultas externas.'
    )
    with op.batch_alter_table('inspector_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inspector_log_token'), ['token_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inspector_log_client'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inspector_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('idx_inspector_log_accessed'), [sa.literal_column('accessed_at DESC')], unique=False)

    op.create_table('time_record_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('change_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], name=op.f('time_record_audit_log_changed_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('time_record_audit_log_pkey'))
    )
    with op.batch_alter_table('time_record_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_log_time_record'), ['time_record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_changed_at'), [sa.literal_column('changed_at DESC')], unique=False)

    # ### end Alembic commands ###
