"""Agregar campos para evitar notificaciones duplicadas

Revision ID: b6ca4ef471ba
Revises: add_theme_preference
Create Date: 2025-11-05 09:03:49.127422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ca4ef471ba'
down_revision = 'add_theme_preference'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_entry_notification_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_exit_notification_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_exit_notification_sent')
        batch_op.drop_column('last_entry_notification_sent')

    # ### end Alembic commands ###
